# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7
  gh: circleci/github-cli@2.0

jobs:
  build:
    executor:
      name: node/default
      tag: '18.7'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run build
      - run:
          command: zip -m pispotter.zip build/*
      - store_artifacts:
          path: pispotter.zip
          destination: build

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build
      - gh/release:
          context:
            - GITHUB_CREDS
          filters:
            branches:
              only:
                - master
          notes-file: README.md
          files: pispotter.zip
          requires:
            - build
          tag: $CIRCLE_BUILD_NUM
          title: Auto-Release from Circle CI
