export const countries = [
  {
    start: "AAA",
    end: "ALZ",
    name: "United States",
    match_name: "United States",
    country_code: "US",
  },
  {
    start: "AMA",
    end: "AOZ",
    name: "Spain",
    match_name: "Spain",
    country_code: "ES",
  },
  {
    start: "APA",
    end: "ASZ",
    name: "Pakistan (Islamic Republic of)",
    match_name: "Pakistan",
    country_code: "PK",
  },
  {
    start: "ATA",
    end: "AWZ",
    name: "India (Republic of)",
    match_name: "India",
    country_code: "IN",
  },
  {
    start: "AXA",
    end: "AXZ",
    name: "Australia",
    match_name: "Australia",
    country_code: "AU",
  },
  {
    start: "AYA",
    end: "AZZ",
    name: "Argentine Republic",
    match_name: "Argentina",
    country_code: "AR",
  },
  {
    start: "A2A",
    end: "A2Z",
    name: "Botswana (Republic of)",
    match_name: "Botswana",
    country_code: "BW",
  },
  {
    start: "A3A",
    end: "A3Z",
    name: "Tonga (Kingdom of)",
    match_name: "Tonga",
    country_code: "TO",
  },
  {
    start: "A4A",
    end: "A4Z",
    name: "Oman (Sultanate of)",
    match_name: "Oman",
    country_code: "OM",
  },
  {
    start: "A5A",
    end: "A5Z",
    name: "Bhutan (Kingdom of)",
    match_name: "Bhutan",
    country_code: "BT",
  },
  {
    start: "A6A",
    end: "A6Z",
    name: "United Arab Emirates",
    match_name: "United Arab Emirates",
    country_code: "AE",
  },
  {
    start: "A7A",
    end: "A7Z",
    name: "Qatar (State of)",
    match_name: "Qatar",
    country_code: "QA",
  },
  {
    start: "A8A",
    end: "A8Z",
    name: "Liberia (Republic of)",
    match_name: "Liberia",
    country_code: "LR",
  },
  {
    start: "A9A",
    end: "A9Z",
    name: "Bahrain (State of)",
    match_name: "Bahrain",
    country_code: "BH",
  },
  {
    start: "BAA",
    end: "BZZ",
    name: "China (People's Republic of)",
    match_name: "China",
    country_code: "CN",
  },
  {
    start: "CAA",
    end: "CEZ",
    name: "Chile",
    match_name: "Chile",
    country_code: "CL",
  },
  {
    start: "CFA",
    end: "CKZ",
    name: "Canada",
    match_name: "Canada",
    country_code: "CA",
  },
  {
    start: "CLA",
    end: "CMZ",
    name: "Cuba",
    match_name: "Cuba",
    country_code: "CU",
  },
  {
    start: "CNA",
    end: "CNZ",
    name: "Morocco (Kingdom of)",
    match_name: "Morocco",
    country_code: "MA",
  },
  {
    start: "COA",
    end: "COZ",
    name: "Cuba",
    match_name: "Cuba",
    country_code: "CU",
  },
  {
    start: "CPA",
    end: "CPZ",
    name: "Bolivia (Republic of)",
    match_name: "Bolivia",
    country_code: "BO",
  },
  {
    start: "CQA",
    end: "CUZ",
    name: "Portugal",
    match_name: "Portugal",
    country_code: "PT",
  },
  {
    start: "CVA",
    end: "CXZ",
    name: "Uruguay (Eastern Republic of)",
    match_name: "Uruguay",
    country_code: "UY",
  },
  {
    start: "CYA",
    end: "CZZ",
    name: "Canada",
    match_name: "Canada",
    country_code: "CA",
  },
  {
    start: "C2A",
    end: "C2Z",
    name: "Nauru (Republic of)",
    match_name: "Nauru",
    country_code: "NR",
  },
  {
    start: "C3A",
    end: "C3Z",
    name: "Andorra (Principality of)",
    match_name: "Andorra",
    country_code: "AD",
  },
  {
    start: "C4A",
    end: "C4Z",
    name: "Cyprus (Republic of)",
    match_name: "Cyprus",
    country_code: "CY",
  },
  {
    start: "C5A",
    end: "C5Z",
    name: "Gambia (Republic of the)",
    match_name: "Gambia",
    country_code: "GM",
  },
  {
    start: "C6A",
    end: "C6Z",
    name: "Bahamas (Commonwealth of the)",
    match_name: "Bahamas",
    country_code: "BS",
  },
  {
    start: "C71",
    end: "C7Z",
    name: "World Meteorological Organization",
    match_name: "Western Sahara",
    country_code: "EH",
  },
  {
    start: "C8A",
    end: "C9Z",
    name: "Mozambique (Republic of)",
    match_name: "Mozambique",
    country_code: "MZ",
  },
  {
    start: "DAA",
    end: "DRZ",
    name: "Germany (Federal Republic of)",
    match_name: "Germany",
    country_code: "DE",
  },
  {
    start: "DSA",
    end: "DTZ",
    name: "Korea (Republic of)",
    match_name: "Kiribati",
    country_code: "KI",
  },
  {
    start: "DUA",
    end: "DZZ",
    name: "Philippines (Republic of the)",
    match_name: "Philippines",
    country_code: "PH",
  },
  {
    start: "D2A",
    end: "D3Z",
    name: "Angola (Republic of)",
    match_name: "Angola",
    country_code: "AO",
  },
  {
    start: "D4A",
    end: "D4Z",
    name: "Cape Verde (Republic of)",
    match_name: "Cape Verde",
    country_code: "CV",
  },
  {
    start: "D5A",
    end: "D5Z",
    name: "Liberia (Republic of)",
    match_name: "Liberia",
    country_code: "LR",
  },
  {
    start: "D6A",
    end: "D6Z",
    name: "Comoros (Islamic Federal Republic of the)",
    match_name: "Comoros",
    country_code: "KM",
  },
  {
    start: "D7A",
    end: "D9Z",
    name: "Korea (Republic of)",
    match_name: "Kiribati",
    country_code: "KI",
  },
  {
    start: "EAA",
    end: "EHZ",
    name: "Spain",
    match_name: "Spain",
    country_code: "ES",
  },
  {
    start: "EIA",
    end: "EJZ",
    name: "Ireland",
    match_name: "Ireland",
    country_code: "IE",
  },
  {
    start: "EKA",
    end: "EKZ",
    name: "Armenia (Republic of)",
    match_name: "Armenia",
    country_code: "AM",
  },
  {
    start: "ELA",
    end: "ELZ",
    name: "Liberia (Republic of)",
    match_name: "Liberia",
    country_code: "LR",
  },
  {
    start: "EMA",
    end: "EOZ",
    name: "Ukraine",
    match_name: "Ukraine",
    country_code: "UA",
  },
  {
    start: "EPA",
    end: "EQZ",
    name: "Iran (Islamic Republic of)",
    match_name: "Indonesia",
    country_code: "ID",
  },
  {
    start: "ERA",
    end: "ERZ",
    name: "Moldova (Republic of)",
    match_name: "Micronesia, Federated States of",
    country_code: "FM",
  },
  {
    start: "ESA",
    end: "ESZ",
    name: "Estonia (Republic of)",
    match_name: "Estonia",
    country_code: "EE",
  },
  {
    start: "ETA",
    end: "ETZ",
    name: "Ethiopia (Federal Democratic Republic of)",
    match_name: "Ethiopia",
    country_code: "ET",
  },
  {
    start: "EUA",
    end: "EWZ",
    name: "Belarus (Republic of)",
    match_name: "Belarus",
    country_code: "BY",
  },
  {
    start: "EXA",
    end: "EXZ",
    name: "Kyrgyz Republic",
    match_name: "Kuwait",
    country_code: "KW",
  },
  {
    start: "EYA",
    end: "EYZ",
    name: "Tajikistan (Republic of)",
    match_name: "Tajikistan",
    country_code: "TJ",
  },
  {
    start: "EZA",
    end: "EZZ",
    name: "Turkmenistan",
    match_name: "Turkmenistan",
    country_code: "TM",
  },
  {
    start: "E2A",
    end: "E2Z",
    name: "Thailand",
    match_name: "Thailand",
    country_code: "TH",
  },
  {
    start: "E3A",
    end: "E3Z",
    name: "Eritrea",
    match_name: "Eritrea",
    country_code: "ER",
  },
  {
    start: "E4A",
    end: "E4Z",
    name: "Palestinian Authority",
    match_name: "Palau",
    country_code: "PW",
  },
  {
    start: "E5A",
    end: "E5Z",
    name: "New Zealand - Cook Island",
    match_name: "New Zealand",
    country_code: "NZ",
  },
  {
    start: "E6A",
    end: "E6Z",
    name: "New Zealand - Niue",
    match_name: "New Zealand",
    country_code: "NZ",
  },
  {
    start: "E7A",
    end: "E7Z",
    name: "Bosnia and Herzegovina (Republic of)",
    match_name: "Bosnia and Herzegovina",
    country_code: "BA",
  },
  {
    start: "FAA",
    end: "FZZ",
    name: "France",
    match_name: "France",
    country_code: "FR",
  },
  {
    start: "GAA",
    end: "GZZ",
    name: "United Kingdom of Great Britain and Northern Ireland",
    match_name: "United Kingdom",
    country_code: "GB",
  },
  {
    start: "HAA",
    end: "HAZ",
    name: "Hungary (Republic of)",
    match_name: "Hungary",
    country_code: "HU",
  },
  {
    start: "HBA",
    end: "HBZ",
    name: "Switzerland (Confederation of)",
    match_name: "Switzerland",
    country_code: "CH",
  },
  {
    start: "HCA",
    end: "HDZ",
    name: "Ecuador",
    match_name: "Ecuador",
    country_code: "EC",
  },
  {
    start: "HEA",
    end: "HEZ",
    name: "Switzerland (Confederation of)",
    match_name: "Switzerland",
    country_code: "CH",
  },
  {
    start: "HFA",
    end: "HFZ",
    name: "Poland (Republic of)",
    match_name: "Poland",
    country_code: "PL",
  },
  {
    start: "HGA",
    end: "HGZ",
    name: "Hungary (Republic of)",
    match_name: "Hungary",
    country_code: "HU",
  },
  {
    start: "HHA",
    end: "HHZ",
    name: "Haiti (Republic of)",
    match_name: "Haiti",
    country_code: "HT",
  },
  {
    start: "HIA",
    end: "HIZ",
    name: "Dominican Republic",
    match_name: "Dominican Republic",
    country_code: "DO",
  },
  {
    start: "HJA",
    end: "HKZ",
    name: "Colombia (Republic of)",
    match_name: "Colombia",
    country_code: "CO",
  },
  {
    start: "HLA",
    end: "HLZ",
    name: "Korea (Republic of)",
    match_name: "Kiribati",
    country_code: "KI",
  },
  {
    start: "HMA",
    end: "HMZ",
    name: "Democratic People's Republic of Korea",
    match_name: "Czech Republic",
    country_code: "CZ",
  },
  {
    start: "HNA",
    end: "HNZ",
    name: "Iraq (Republic of)",
    match_name: "Iraq",
    country_code: "IQ",
  },
  {
    start: "HOA",
    end: "HPZ",
    name: "Panama (Republic of)",
    match_name: "Panama",
    country_code: "PA",
  },
  {
    start: "HQA",
    end: "HRZ",
    name: "Honduras (Republic of)",
    match_name: "Honduras",
    country_code: "HN",
  },
  {
    start: "HSA",
    end: "HSZ",
    name: "Thailand",
    match_name: "Thailand",
    country_code: "TH",
  },
  {
    start: "HTA",
    end: "HTZ",
    name: "Nicaragua",
    match_name: "Nicaragua",
    country_code: "NI",
  },
  {
    start: "HUA",
    end: "HUZ",
    name: "El Salvador (Republic of)",
    match_name: "El Salvador",
    country_code: "SV",
  },
  {
    start: "HVA",
    end: "HVZ",
    name: "Vatican City State",
    match_name: "Vanuatu",
    country_code: "VU",
  },
  {
    start: "HWA",
    end: "HYZ",
    name: "France",
    match_name: "France",
    country_code: "FR",
  },
  {
    start: "HZA",
    end: "HZZ",
    name: "Saudi Arabia (Kingdom of)",
    match_name: "Saudi Arabia",
    country_code: "SA",
  },
  {
    start: "H2A",
    end: "H2Z",
    name: "Cyprus (Republic of)",
    match_name: "Cyprus",
    country_code: "CY",
  },
  {
    start: "H3A",
    end: "H3Z",
    name: "Panama (Republic of)",
    match_name: "Panama",
    country_code: "PA",
  },
  {
    start: "H4A",
    end: "H4Z",
    name: "Solomon Islands",
    match_name: "Solomon Islands",
    country_code: "SB",
  },
  {
    start: "H6A",
    end: "H7Z",
    name: "Nicaragua",
    match_name: "Nicaragua",
    country_code: "NI",
  },
  {
    start: "H8A",
    end: "H9Z",
    name: "Panama (Republic of)",
    match_name: "Panama",
    country_code: "PA",
  },
  {
    start: "IAA",
    end: "IZZ",
    name: "Italy",
    match_name: "Italy",
    country_code: "IT",
  },
  {
    start: "JAA",
    end: "JSZ",
    name: "Japan",
    match_name: "Japan",
    country_code: "JP",
  },
  {
    start: "JTA",
    end: "JVZ",
    name: "Mongolia",
    match_name: "Mongolia",
    country_code: "MN",
  },
  {
    start: "JWA",
    end: "JXZ",
    name: "Norway",
    match_name: "Norway",
    country_code: "NO",
  },
  {
    start: "JYA",
    end: "JYZ",
    name: "Jordan (Hashemite Kingdom of)",
    match_name: "Jordan",
    country_code: "JO",
  },
  {
    start: "JZA",
    end: "JZZ",
    name: "Indonesia (Republic of)",
    match_name: "Indonesia",
    country_code: "ID",
  },
  {
    start: "J2A",
    end: "J2Z",
    name: "Djibouti (Republic of)",
    match_name: "Djibouti",
    country_code: "DJ",
  },
  {
    start: "J3A",
    end: "J3Z",
    name: "Grenada",
    match_name: "Grenada",
    country_code: "GD",
  },
  {
    start: "J4A",
    end: "J4Z",
    name: "Greece",
    match_name: "Greece",
    country_code: "GR",
  },
  {
    start: "J5A",
    end: "J5Z",
    name: "Guinea-Bissau (Republic of)",
    match_name: "Guinea-Bissau",
    country_code: "GW",
  },
  {
    start: "J6A",
    end: "J6Z",
    name: "Saint Lucia",
    match_name: "Saint Lucia",
    country_code: "LC",
  },
  {
    start: "J7A",
    end: "J7Z",
    name: "Dominica (Commonwealth of)",
    match_name: "Dominica",
    country_code: "DM",
  },
  {
    start: "J8A",
    end: "J8Z",
    name: "Saint Vincent and the Grenadines",
    match_name: "Saint Vincent and the Grenadines",
    country_code: "VC",
  },
  {
    start: "KAA",
    end: "KZZ",
    name: "United States of America",
    match_name: "United States",
    country_code: "US",
  },
  {
    start: "LAA",
    end: "LNZ",
    name: "Norway",
    match_name: "Norway",
    country_code: "NO",
  },
  {
    start: "LOA",
    end: "LWZ",
    name: "Argentine Republic",
    match_name: "Argentina",
    country_code: "AR",
  },
  {
    start: "LXA",
    end: "LXZ",
    name: "Luxembourg",
    match_name: "Luxembourg",
    country_code: "LU",
  },
  {
    start: "LYA",
    end: "LYZ",
    name: "Lithuania (Republic of)",
    match_name: "Lithuania",
    country_code: "LT",
  },
  {
    start: "LZA",
    end: "LZZ",
    name: "Bulgaria (Republic of)",
    match_name: "Bulgaria",
    country_code: "BG",
  },
  {
    start: "L2A",
    end: "L9Z",
    name: "Argentine Republic",
    match_name: "Argentina",
    country_code: "AR",
  },
  {
    start: "MAA",
    end: "MZZ",
    name: "United Kingdom of Great Britain and Northern Ireland",
    match_name: "United Kingdom",
    country_code: "GB",
  },
  {
    start: "NAA",
    end: "NZZ",
    name: "United States of America",
    match_name: "United States",
    country_code: "US",
  },
  {
    start: "OAA",
    end: "OCZ",
    name: "Peru",
    match_name: "Peru",
    country_code: "PE",
  },
  {
    start: "ODA",
    end: "ODZ",
    name: "Lebanon",
    match_name: "Lebanon",
    country_code: "LB",
  },
  {
    start: "OEA",
    end: "OEZ",
    name: "Austria",
    match_name: "Austria",
    country_code: "AT",
  },
  {
    start: "OFA",
    end: "OJZ",
    name: "Finland",
    match_name: "Finland",
    country_code: "FI",
  },
  {
    start: "OKA",
    end: "OLZ",
    name: "Czech Republic",
    match_name: "Czech Republic",
    country_code: "CZ",
  },
  {
    start: "OMA",
    end: "OMZ",
    name: "Slovak Republic",
    match_name: "Sint Maarten (Dutch part)",
    country_code: "SX",
  },
  {
    start: "ONA",
    end: "OTZ",
    name: "Belgium",
    match_name: "Belgium",
    country_code: "BE",
  },
  {
    start: "OUA",
    end: "OZZ",
    name: "Denmark",
    match_name: "Denmark",
    country_code: "DK",
  },
  {
    start: "PAA",
    end: "PIZ",
    name: "Netherlands (Kingdom of the)",
    match_name: "Netherlands",
    country_code: "NL",
  },
  {
    start: "PJA",
    end: "PJZ",
    name: "Netherlands (Kingdom of the) - Netherlands Caribbean",
    match_name: "Netherlands",
    country_code: "NL",
  },
  {
    start: "PKA",
    end: "POZ",
    name: "Indonesia (Republic of)",
    match_name: "Indonesia",
    country_code: "ID",
  },
  {
    start: "PPA",
    end: "PYZ",
    name: "Brazil (Federative Republic of)",
    match_name: "Brazil",
    country_code: "BR",
  },
  {
    start: "PZA",
    end: "PZZ",
    name: "Suriname (Republic of)",
    match_name: "Suriname",
    country_code: "SR",
  },
  {
    start: "P2A",
    end: "P2Z",
    name: "Papua New Guinea",
    match_name: "Papua New Guinea",
    country_code: "PG",
  },
  {
    start: "P3A",
    end: "P3Z",
    name: "Cyprus (Republic of)",
    match_name: "Cyprus",
    country_code: "CY",
  },
  {
    start: "P4A",
    end: "P4Z",
    name: "Netherlands (Kingdom of the) - Aruba",
    match_name: "Netherlands",
    country_code: "NL",
  },
  {
    start: "P5A",
    end: "P9Z",
    name: "Democratic People's Republic of Korea",
    match_name: "Czech Republic",
    country_code: "CZ",
  },
  {
    start: "RAA",
    end: "RZZ",
    name: "Russian Federation",
    match_name: "Russian Federation",
    country_code: "RU",
  },
  {
    start: "SAA",
    end: "SMZ",
    name: "Sweden",
    match_name: "Sweden",
    country_code: "SE",
  },
  {
    start: "SNA",
    end: "SRZ",
    name: "Poland (Republic of)",
    match_name: "Poland",
    country_code: "PL",
  },
  {
    start: "SSA",
    end: "SSM",
    name: "Egypt (Arab Republic of)",
    match_name: "Egypt",
    country_code: "EG",
  },
  {
    start: "SSN",
    end: "STZ",
    name: "Sudan (Republic of the)",
    match_name: "Sudan",
    country_code: "SD",
  },
  {
    start: "SUA",
    end: "SUZ",
    name: "Egypt (Arab Republic of)",
    match_name: "Egypt",
    country_code: "EG",
  },
  {
    start: "SVA",
    end: "SZZ",
    name: "Greece",
    match_name: "Greece",
    country_code: "GR",
  },
  {
    start: "S2A",
    end: "S3Z",
    name: "Bangladesh (People's Republic of)",
    match_name: "Bangladesh",
    country_code: "BD",
  },
  {
    start: "S5A",
    end: "S5Z",
    name: "Slovenia (Republic of)",
    match_name: "Slovenia",
    country_code: "SI",
  },
  {
    start: "S6A",
    end: "S6Z",
    name: "Singapore (Republic of)",
    match_name: "Singapore",
    country_code: "SG",
  },
  {
    start: "S7A",
    end: "S7Z",
    name: "Seychelles (Republic of)",
    match_name: "Seychelles",
    country_code: "SC",
  },
  {
    start: "S8A",
    end: "S8Z",
    name: "South Africa (Republic of)",
    match_name: "South Africa",
    country_code: "ZA",
  },
  {
    start: "S9A",
    end: "S9Z",
    name: "Sao Tome and Principe (Democratic Republic of)",
    match_name: "Sao Tome and Principe",
    country_code: "ST",
  },
  {
    start: "TAA",
    end: "TCZ",
    name: "Turkey",
    match_name: "Turkey",
    country_code: "TR",
  },
  {
    start: "TDA",
    end: "TDZ",
    name: "Guatemala (Republic of)",
    match_name: "Guatemala",
    country_code: "GT",
  },
  {
    start: "TEA",
    end: "TEZ",
    name: "Costa Rica",
    match_name: "Costa Rica",
    country_code: "CR",
  },
  {
    start: "TFA",
    end: "TFZ",
    name: "Iceland",
    match_name: "Iceland",
    country_code: "IS",
  },
  {
    start: "TGA",
    end: "TGZ",
    name: "Guatemala (Republic of)",
    match_name: "Guatemala",
    country_code: "GT",
  },
  {
    start: "THA",
    end: "THZ",
    name: "France",
    match_name: "France",
    country_code: "FR",
  },
  {
    start: "TIA",
    end: "TIZ",
    name: "Costa Rica",
    match_name: "Costa Rica",
    country_code: "CR",
  },
  {
    start: "TJA",
    end: "TJZ",
    name: "Cameroon (Republic of)",
    match_name: "Cameroon",
    country_code: "CM",
  },
  {
    start: "TKA",
    end: "TKZ",
    name: "France",
    match_name: "France",
    country_code: "FR",
  },
  {
    start: "TLA",
    end: "TLZ",
    name: "Central African Republic",
    match_name: "Central African Republic",
    country_code: "CF",
  },
  {
    start: "TMA",
    end: "TMZ",
    name: "France",
    match_name: "France",
    country_code: "FR",
  },
  {
    start: "TNA",
    end: "TNZ",
    name: "Congo (Republic of the)",
    match_name: "Congo",
    country_code: "CG",
  },
  {
    start: "TOA",
    end: "TQZ",
    name: "France",
    match_name: "France",
    country_code: "FR",
  },
  {
    start: "TRA",
    end: "TRZ",
    name: "Gabonese Republic",
    match_name: "Gabon",
    country_code: "GA",
  },
  {
    start: "TSA",
    end: "TSZ",
    name: "Tunisia",
    match_name: "Tunisia",
    country_code: "TN",
  },
  {
    start: "TTA",
    end: "TTZ",
    name: "Chad (Republic of)",
    match_name: "Chad",
    country_code: "TD",
  },
  {
    start: "TUA",
    end: "TUZ",
    name: "Côte d'Ivoire (Republic of)",
    match_name: "Côte d'Ivoire",
    country_code: "CI",
  },
  {
    start: "TVA",
    end: "TXZ",
    name: "France",
    match_name: "France",
    country_code: "FR",
  },
  {
    start: "TYA",
    end: "TYZ",
    name: "Benin (Republic of)",
    match_name: "Benin",
    country_code: "BJ",
  },
  {
    start: "TZA",
    end: "TZZ",
    name: "Mali (Republic of)",
    match_name: "Mali",
    country_code: "ML",
  },
  {
    start: "T2A",
    end: "T2Z",
    name: "Tuvalu",
    match_name: "Tuvalu",
    country_code: "TV",
  },
  {
    start: "T3A",
    end: "T3Z",
    name: "Kiribati (Republic of)",
    match_name: "Kiribati",
    country_code: "KI",
  },
  {
    start: "T4A",
    end: "T4Z",
    name: "Cuba",
    match_name: "Cuba",
    country_code: "CU",
  },
  {
    start: "T5A",
    end: "T5Z",
    name: "Somali Democratic Republic",
    match_name: "Solomon Islands",
    country_code: "SB",
  },
  {
    start: "T6A",
    end: "T6Z",
    name: "Afghanistan (Islamic State of)",
    match_name: "Afghanistan",
    country_code: "AF",
  },
  {
    start: "T7A",
    end: "T7Z",
    name: "San Marino (Republic of)",
    match_name: "San Marino",
    country_code: "SM",
  },
  {
    start: "T8A",
    end: "T8Z",
    name: "Palau (Republic of)",
    match_name: "Palau",
    country_code: "PW",
  },
  {
    start: "UAA",
    end: "UIZ",
    name: "Russian Federation",
    match_name: "Russian Federation",
    country_code: "RU",
  },
  {
    start: "UJA",
    end: "UMZ",
    name: "Uzbekistan (Republic of)",
    match_name: "Uzbekistan",
    country_code: "UZ",
  },
  {
    start: "UNA",
    end: "UQZ",
    name: "Kazakhstan (Republic of)",
    match_name: "Kazakhstan",
    country_code: "KZ",
  },
  {
    start: "URA",
    end: "UZZ",
    name: "Ukraine",
    match_name: "Ukraine",
    country_code: "UA",
  },
  {
    start: "VAA",
    end: "VGZ",
    name: "Canada",
    match_name: "Canada",
    country_code: "CA",
  },
  {
    start: "VHA",
    end: "VNZ",
    name: "Australia",
    match_name: "Australia",
    country_code: "AU",
  },
  {
    start: "VOA",
    end: "VOZ",
    name: "Canada",
    match_name: "Canada",
    country_code: "CA",
  },
  {
    start: "VPA",
    end: "VQZ",
    name: "United Kingdom of Great Britain and Northern Ireland",
    match_name: "United Kingdom",
    country_code: "GB",
  },
  {
    start: "VRA",
    end: "VRZ",
    name: "China (People's Republic of) - Hong Kong",
    match_name: "China",
    country_code: "CN",
  },
  {
    start: "VSA",
    end: "VSZ",
    name: "United Kingdom of Great Britain and Northern Ireland",
    match_name: "United Kingdom",
    country_code: "GB",
  },
  {
    start: "VTA",
    end: "VWZ",
    name: "India (Republic of)",
    match_name: "India",
    country_code: "IN",
  },
  {
    start: "VXA",
    end: "VYZ",
    name: "Canada",
    match_name: "Canada",
    country_code: "CA",
  },
  {
    start: "VZA",
    end: "VZZ",
    name: "Australia",
    match_name: "Australia",
    country_code: "AU",
  },
  {
    start: "V2A",
    end: "V2Z",
    name: "Antigua and Barbuda",
    match_name: "Antigua and Barbuda",
    country_code: "AG",
  },
  {
    start: "V3A",
    end: "V3Z",
    name: "Belize",
    match_name: "Belize",
    country_code: "BZ",
  },
  {
    start: "V4A",
    end: "V4Z",
    name: "Saint Kitts and Nevis",
    match_name: "Saint Kitts and Nevis",
    country_code: "KN",
  },
  {
    start: "V5A",
    end: "V5Z",
    name: "Namibia (Republic of)",
    match_name: "Namibia",
    country_code: "NA",
  },
  {
    start: "V6A",
    end: "V6Z",
    name: "Micronesia (Federated States of)",
    match_name: "Mexico",
    country_code: "MX",
  },
  {
    start: "V7A",
    end: "V7Z",
    name: "Marshall Islands (Republic of the)",
    match_name: "Marshall Islands",
    country_code: "MH",
  },
  {
    start: "V8A",
    end: "V8Z",
    name: "Brunei Darussalam",
    match_name: "Brunei Darussalam",
    country_code: "BN",
  },
  {
    start: "WAA",
    end: "WZZ",
    name: "United States of America",
    match_name: "United States",
    country_code: "US",
  },
  {
    start: "XAA",
    end: "XIZ",
    name: "Mexico",
    match_name: "Mexico",
    country_code: "MX",
  },
  {
    start: "XJA",
    end: "XOZ",
    name: "Canada",
    match_name: "Canada",
    country_code: "CA",
  },
  {
    start: "XPA",
    end: "XPZ",
    name: "Denmark",
    match_name: "Denmark",
    country_code: "DK",
  },
  {
    start: "XQA",
    end: "XRZ",
    name: "Chile",
    match_name: "Chile",
    country_code: "CL",
  },
  {
    start: "XSA",
    end: "XSZ",
    name: "China (People's Republic of)",
    match_name: "China",
    country_code: "CN",
  },
  {
    start: "XTA",
    end: "XTZ",
    name: "Burkina Faso",
    match_name: "Burkina Faso",
    country_code: "BF",
  },
  {
    start: "XUA",
    end: "XUZ",
    name: "Cambodia (Kingdom of)",
    match_name: "Cambodia",
    country_code: "KH",
  },
  {
    start: "XVA",
    end: "XVZ",
    name: "Viet Nam (Socialist Republic of)",
    match_name: "Venezuela",
    country_code: "VE",
  },
  {
    start: "XWA",
    end: "XWZ",
    name: "Lao People's Democratic Republic",
    match_name: "Lao People's Democratic Republic",
    country_code: "LA",
  },
  {
    start: "XXA",
    end: "XXZ",
    name: "China (People's Republic of) - Macao",
    match_name: "China",
    country_code: "CN",
  },
  {
    start: "XYA",
    end: "XZZ",
    name: "Myanmar (Union of)",
    match_name: "Myanmar",
    country_code: "MM",
  },
  {
    start: "YAA",
    end: "YAZ",
    name: "Afghanistan (Islamic State of)",
    match_name: "Afghanistan",
    country_code: "AF",
  },
  {
    start: "YBA",
    end: "YHZ",
    name: "Indonesia (Republic of)",
    match_name: "Indonesia",
    country_code: "ID",
  },
  {
    start: "YIA",
    end: "YIZ",
    name: "Iraq (Republic of)",
    match_name: "Iraq",
    country_code: "IQ",
  },
  {
    start: "YJA",
    end: "YJZ",
    name: "Vanuatu (Republic of)",
    match_name: "Vanuatu",
    country_code: "VU",
  },
  {
    start: "YKA",
    end: "YKZ",
    name: "Syrian Arab Republic",
    match_name: "Syrian Arab Republic",
    country_code: "SY",
  },
  {
    start: "YLA",
    end: "YLZ",
    name: "Latvia (Republic of)",
    match_name: "Latvia",
    country_code: "LV",
  },
  {
    start: "YMA",
    end: "YMZ",
    name: "Turkey",
    match_name: "Turkey",
    country_code: "TR",
  },
  {
    start: "YNA",
    end: "YNZ",
    name: "Nicaragua",
    match_name: "Nicaragua",
    country_code: "NI",
  },
  {
    start: "YOA",
    end: "YRZ",
    name: "Romania",
    match_name: "Romania",
    country_code: "RO",
  },
  {
    start: "YSA",
    end: "YSZ",
    name: "El Salvador (Republic of)",
    match_name: "El Salvador",
    country_code: "SV",
  },
  {
    start: "YTA",
    end: "YUZ",
    name: "Serbia (Republic of)",
    match_name: "Serbia",
    country_code: "RS",
  },
  {
    start: "YVA",
    end: "YYZ",
    name: "Venezuela (Republic of)",
    match_name: "Venezuela",
    country_code: "VE",
  },
  {
    start: "Y2A",
    end: "Y9Z",
    name: "Germany (Federal Republic of)",
    match_name: "Germany",
    country_code: "DE",
  },
  {
    start: "ZAA",
    end: "ZAZ",
    name: "Albania (Republic of)",
    match_name: "Albania",
    country_code: "AL",
  },
  {
    start: "ZBA",
    end: "ZJZ",
    name: "United Kingdom of Great Britain and Northern Ireland",
    match_name: "United Kingdom",
    country_code: "GB",
  },
  {
    start: "ZKA",
    end: "ZMZ",
    name: "New Zealand",
    match_name: "New Zealand",
    country_code: "NZ",
  },
  {
    start: "ZNA",
    end: "ZOZ",
    name: "United Kingdom of Great Britain and Northern Ireland",
    match_name: "United Kingdom",
    country_code: "GB",
  },
  {
    start: "ZPA",
    end: "ZPZ",
    name: "Paraguay (Republic of)",
    match_name: "Paraguay",
    country_code: "PY",
  },
  {
    start: "ZQA",
    end: "ZQZ",
    name: "United Kingdom of Great Britain and Northern Ireland",
    match_name: "United Kingdom",
    country_code: "GB",
  },
  {
    start: "ZRA",
    end: "ZUZ",
    name: "South Africa (Republic of)",
    match_name: "South Africa",
    country_code: "ZA",
  },
  {
    start: "ZVA",
    end: "ZZZ",
    name: "Brazil (Federative Republic of)",
    match_name: "Brazil",
    country_code: "BR",
  },
  {
    start: "Z2A",
    end: "Z2Z",
    name: "Zimbabwe (Republic of)",
    match_name: "Zimbabwe",
    country_code: "ZW",
  },
  {
    start: "Z3A",
    end: "Z3Z",
    name: "North Macedonia (Republic of)",
    match_name: "Norfolk Island",
    country_code: "NF",
  },
  {
    start: "Z6A",
    end: "Z6Z",
    name: "Kosovo (Republic of)",
    match_name: "Korea, Republic of",
    country_code: "KR",
  },
  {
    start: "Z8A",
    end: "Z8Z",
    name: "South Sudan (Republic of)",
    match_name: "South Sudan",
    country_code: "SS",
  },
  {
    start: "2AA",
    end: "2ZZ",
    name: "United Kingdom of Great Britain and Northern Ireland",
    match_name: "United Kingdom",
    country_code: "GB",
  },
  {
    start: "3AA",
    end: "3AZ",
    name: "Monaco (Principality of)",
    match_name: "Monaco",
    country_code: "MC",
  },
  {
    start: "3BA",
    end: "3BZ",
    name: "Mauritius (Republic of)",
    match_name: "Mauritius",
    country_code: "MU",
  },
  {
    start: "3CA",
    end: "3CZ",
    name: "Equatorial Guinea (Republic of)",
    match_name: "Equatorial Guinea",
    country_code: "GQ",
  },
  {
    start: "3DA",
    end: "3DM",
    name: "Kingdom of Eswatini",
    match_name: "Kenya",
    country_code: "KE",
  },
  {
    start: "3DN",
    end: "3DZ",
    name: "Fiji (Republic of)",
    match_name: "Fiji",
    country_code: "FJ",
  },
  {
    start: "3EA",
    end: "3FZ",
    name: "Panama (Republic of)",
    match_name: "Panama",
    country_code: "PA",
  },
  {
    start: "3GA",
    end: "3GZ",
    name: "Chile",
    match_name: "Chile",
    country_code: "CL",
  },
  {
    start: "3HA",
    end: "3UZ",
    name: "China (People's Republic of)",
    match_name: "China",
    country_code: "CN",
  },
  {
    start: "3VA",
    end: "3VZ",
    name: "Tunisia",
    match_name: "Tunisia",
    country_code: "TN",
  },
  {
    start: "3WA",
    end: "3WZ",
    name: "Viet Nam (Socialist Republic of)",
    match_name: "Venezuela",
    country_code: "VE",
  },
  {
    start: "3XA",
    end: "3XZ",
    name: "Guinea (Republic of)",
    match_name: "Guinea",
    country_code: "GN",
  },
  {
    start: "3YA",
    end: "3YZ",
    name: "Norway",
    match_name: "Norway",
    country_code: "NO",
  },
  {
    start: "3ZA",
    end: "3ZZ",
    name: "Poland (Republic of)",
    match_name: "Poland",
    country_code: "PL",
  },
  {
    start: "4AA",
    end: "4CZ",
    name: "Mexico",
    match_name: "Mexico",
    country_code: "MX",
  },
  {
    start: "4DA",
    end: "4IZ",
    name: "Philippines (Republic of the)",
    match_name: "Philippines",
    country_code: "PH",
  },
  {
    start: "4JA",
    end: "4KZ",
    name: "Azerbaijani Republic",
    match_name: "Azerbaijan",
    country_code: "AZ",
  },
  {
    start: "4LA",
    end: "4LZ",
    name: "Georgia (Republic of)",
    match_name: "Georgia",
    country_code: "GE",
  },
  {
    start: "4MA",
    end: "4MZ",
    name: "Venezuela (Republic of)",
    match_name: "Venezuela",
    country_code: "VE",
  },
  {
    start: "4OA",
    end: "4OZ",
    name: "Montenegro (Republic of)                   (WRC-07)",
    match_name: "Montenegro",
    country_code: "ME",
  },
  {
    start: "4PA",
    end: "4SZ",
    name: "Sri Lanka (Democratic Socialist Republic of)",
    match_name: "Sri Lanka",
    country_code: "LK",
  },
  {
    start: "4TA",
    end: "4TZ",
    name: "Peru",
    match_name: "Peru",
    country_code: "PE",
  },
  {
    start: "4UA",
    end: "4UZ",
    name: "United Nations",
    match_name: "United Kingdom",
    country_code: "GB",
  },
  {
    start: "4VA",
    end: "4VZ",
    name: "Haiti (Republic of)",
    match_name: "Haiti",
    country_code: "HT",
  },
  {
    start: "4WA",
    end: "4WZ",
    name: "Democratic Republic of Timor-Leste   (WRC-03)",
    match_name: "Czech Republic",
    country_code: "CZ",
  },
  {
    start: "4XA",
    end: "4XZ",
    name: "Israel (State of)",
    match_name: "Israel",
    country_code: "IL",
  },
  {
    start: "4YA",
    end: "4YZ",
    name: "International Civil Aviation Organization",
    match_name: "Indonesia",
    country_code: "ID",
  },
  {
    start: "4ZA",
    end: "4ZZ",
    name: "Israel (State of)",
    match_name: "Israel",
    country_code: "IL",
  },
  {
    start: "5AA",
    end: "5AZ",
    name: "Libya (Socialist People's Libyan Arab Jamahiriya)",
    match_name: "Liberia",
    country_code: "LR",
  },
  {
    start: "5BA",
    end: "5BZ",
    name: "Cyprus (Republic of)",
    match_name: "Cyprus",
    country_code: "CY",
  },
  {
    start: "5CA",
    end: "5GZ",
    name: "Morocco (Kingdom of)",
    match_name: "Morocco",
    country_code: "MA",
  },
  {
    start: "5HA",
    end: "5IZ",
    name: "Tanzania (United Republic of)",
    match_name: "Tajikistan",
    country_code: "TJ",
  },
  {
    start: "5JA",
    end: "5KZ",
    name: "Colombia (Republic of)",
    match_name: "Colombia",
    country_code: "CO",
  },
  {
    start: "5LA",
    end: "5MZ",
    name: "Liberia (Republic of)",
    match_name: "Liberia",
    country_code: "LR",
  },
  {
    start: "5NA",
    end: "5OZ",
    name: "Nigeria (Federal Republic of)",
    match_name: "Nigeria",
    country_code: "NG",
  },
  {
    start: "5PA",
    end: "5QZ",
    name: "Denmark",
    match_name: "Denmark",
    country_code: "DK",
  },
  {
    start: "5RA",
    end: "5SZ",
    name: "Madagascar (Republic of)",
    match_name: "Madagascar",
    country_code: "MG",
  },
  {
    start: "5TA",
    end: "5TZ",
    name: "Mauritania (Islamic Republic of)",
    match_name: "Mauritania",
    country_code: "MR",
  },
  {
    start: "5UA",
    end: "5UZ",
    name: "Niger (Republic of the)",
    match_name: "Niger",
    country_code: "NE",
  },
  {
    start: "5VA",
    end: "5VZ",
    name: "Togolese Republic",
    match_name: "Togo",
    country_code: "TG",
  },
  {
    start: "5WA",
    end: "5WZ",
    name: "Samoa (Independent State of)",
    match_name: "Samoa",
    country_code: "WS",
  },
  {
    start: "5XA",
    end: "5XZ",
    name: "Uganda (Republic of)",
    match_name: "Uganda",
    country_code: "UG",
  },
  {
    start: "5YA",
    end: "5ZZ",
    name: "Kenya (Republic of)",
    match_name: "Kenya",
    country_code: "KE",
  },
  {
    start: "6AA",
    end: "6BZ",
    name: "Egypt (Arab Republic of)",
    match_name: "Egypt",
    country_code: "EG",
  },
  {
    start: "6CA",
    end: "6CZ",
    name: "Syrian Arab Republic",
    match_name: "Syrian Arab Republic",
    country_code: "SY",
  },
  {
    start: "6DA",
    end: "6JZ",
    name: "Mexico",
    match_name: "Mexico",
    country_code: "MX",
  },
  {
    start: "6KA",
    end: "6NZ",
    name: "Korea (Republic of)",
    match_name: "Kiribati",
    country_code: "KI",
  },
  {
    start: "6OA",
    end: "6OZ",
    name: "Somali Democratic Republic",
    match_name: "Solomon Islands",
    country_code: "SB",
  },
  {
    start: "6PA",
    end: "6SZ",
    name: "Pakistan (Islamic Republic of)",
    match_name: "Pakistan",
    country_code: "PK",
  },
  {
    start: "6TA",
    end: "6UZ",
    name: "Sudan (Republic of the)",
    match_name: "Sudan",
    country_code: "SD",
  },
  {
    start: "6VA",
    end: "6WZ",
    name: "Senegal (Republic of)",
    match_name: "Senegal",
    country_code: "SN",
  },
  {
    start: "6XA",
    end: "6XZ",
    name: "Madagascar (Republic of)",
    match_name: "Madagascar",
    country_code: "MG",
  },
  {
    start: "6YA",
    end: "6YZ",
    name: "Jamaica",
    match_name: "Jamaica",
    country_code: "JM",
  },
  {
    start: "6ZA",
    end: "6ZZ",
    name: "Liberia (Republic of)",
    match_name: "Liberia",
    country_code: "LR",
  },
  {
    start: "7AA",
    end: "7IZ",
    name: "Indonesia (Republic of)",
    match_name: "Indonesia",
    country_code: "ID",
  },
  {
    start: "7JA",
    end: "7NZ",
    name: "Japan",
    match_name: "Japan",
    country_code: "JP",
  },
  {
    start: "7OA",
    end: "7OZ",
    name: "Yemen (Republic of)",
    match_name: "Yemen",
    country_code: "YE",
  },
  {
    start: "7PA",
    end: "7PZ",
    name: "Lesotho (Kingdom of)",
    match_name: "Lesotho",
    country_code: "LS",
  },
  {
    start: "7QA",
    end: "7QZ",
    name: "Malawi",
    match_name: "Malawi",
    country_code: "MW",
  },
  {
    start: "7RA",
    end: "7RZ",
    name: "Algeria (People's Democratic Republic of)",
    match_name: "Algeria",
    country_code: "DZ",
  },
  {
    start: "7SA",
    end: "7SZ",
    name: "Sweden",
    match_name: "Sweden",
    country_code: "SE",
  },
  {
    start: "7TA",
    end: "7YZ",
    name: "Algeria (People's Democratic Republic of)",
    match_name: "Algeria",
    country_code: "DZ",
  },
  {
    start: "7ZA",
    end: "7ZZ",
    name: "Saudi Arabia (Kingdom of)",
    match_name: "Saudi Arabia",
    country_code: "SA",
  },
  {
    start: "8AA",
    end: "8IZ",
    name: "Indonesia (Republic of)",
    match_name: "Indonesia",
    country_code: "ID",
  },
  {
    start: "8JA",
    end: "8NZ",
    name: "Japan",
    match_name: "Japan",
    country_code: "JP",
  },
  {
    start: "8OA",
    end: "8OZ",
    name: "Botswana (Republic of)",
    match_name: "Botswana",
    country_code: "BW",
  },
  {
    start: "8PA",
    end: "8PZ",
    name: "Barbados",
    match_name: "Barbados",
    country_code: "BB",
  },
  {
    start: "8QA",
    end: "8QZ",
    name: "Maldives (Republic of)",
    match_name: "Maldives",
    country_code: "MV",
  },
  {
    start: "8RA",
    end: "8RZ",
    name: "Guyana",
    match_name: "Guyana",
    country_code: "GY",
  },
  {
    start: "8SA",
    end: "8SZ",
    name: "Sweden",
    match_name: "Sweden",
    country_code: "SE",
  },
  {
    start: "8TA",
    end: "8YZ",
    name: "India (Republic of)",
    match_name: "India",
    country_code: "IN",
  },
  {
    start: "8ZA",
    end: "8ZZ",
    name: "Saudi Arabia (Kingdom of)",
    match_name: "Saudi Arabia",
    country_code: "SA",
  },
  {
    start: "9AA",
    end: "9AZ",
    name: "Croatia (Republic of)",
    match_name: "Croatia",
    country_code: "HR",
  },
  {
    start: "9BA",
    end: "9DZ",
    name: "Iran (Islamic Republic of)",
    match_name: "Indonesia",
    country_code: "ID",
  },
  {
    start: "9EA",
    end: "9FZ",
    name: "Ethiopia (Federal Democratic Republic of)",
    match_name: "Ethiopia",
    country_code: "ET",
  },
  {
    start: "9GA",
    end: "9GZ",
    name: "Ghana",
    match_name: "Ghana",
    country_code: "GH",
  },
  {
    start: "9HA",
    end: "9HZ",
    name: "Malta",
    match_name: "Malta",
    country_code: "MT",
  },
  {
    start: "9IA",
    end: "9JZ",
    name: "Zambia (Republic of)",
    match_name: "Yemen",
    country_code: "YE",
  },
  {
    start: "9KA",
    end: "9KZ",
    name: "Kuwait (State of)",
    match_name: "Kuwait",
    country_code: "KW",
  },
  {
    start: "9LA",
    end: "9LZ",
    name: "Sierra Leone",
    match_name: "Sierra Leone",
    country_code: "SL",
  },
  {
    start: "9MA",
    end: "9MZ",
    name: "Malaysia",
    match_name: "Malaysia",
    country_code: "MY",
  },
  {
    start: "9NA",
    end: "9NZ",
    name: "Nepal",
    match_name: "Nepal",
    country_code: "NP",
  },
  {
    start: "9OA",
    end: "9TZ",
    name: "Democratic Republic of the Congo",
    match_name: "Czech Republic",
    country_code: "CZ",
  },
  {
    start: "9UA",
    end: "9UZ",
    name: "Burundi (Republic of)",
    match_name: "Burundi",
    country_code: "BI",
  },
  {
    start: "9VA",
    end: "9VZ",
    name: "Singapore (Republic of)",
    match_name: "Singapore",
    country_code: "SG",
  },
  {
    start: "9WA",
    end: "9WZ",
    name: "Malaysia",
    match_name: "Malaysia",
    country_code: "MY",
  },
  {
    start: "9XA",
    end: "9XZ",
    name: "Rwandese Republic",
    match_name: "Rwanda",
    country_code: "RW",
  },
  {
    start: "9YA",
    end: "9ZZ",
    name: "Trinidad and Tobago",
    match_name: "Trinidad and Tobago",
    country_code: "TT",
  },
];

const testWithPrefixLength = (callsign, country, length) => {
  if (
    callsign.substring(0, length) >= country.start.substring(0, length) &&
    callsign.substring(0, length) <= country.end.substring(0, length)
  ) {
    return true;
  }
  return false;
};

export const countryForCallsign = (callsign) => {
  let match;

  for (var i = 3; i > 0; i--) {
    // eslint-disable-next-line
    countries.every((c) => {
      if (testWithPrefixLength(callsign, c, i)) {
        match = c;
        return false;
      }
      return true;
    });

    if (match) break;
  }

  return match;
};
